# Jekyll configuration file
# 
# for documentation, see:
# https://jekyllrb.com/docs/configuration/

exclude:
  - README.md
  - package.json
  - package-lock.json
  - js/src
  - styles/_partials
  - node_modules
theme: null
remote-theme: null
plugins:
  - jekyll-redirect-from
sass:
  sass_dir: styles/_partials
repository: decoalitie/desering.org
