# Jekyll configuration file
# 
# for documentation, see:
# https://jekyllrb.com/docs/configuration/

exclude:
  - README.md
  - package.json
  - package-lock.json
  - js/src
  - node_modules
theme: null
remote-theme: null