name: Fetch Playlist Info

on:
  schedule:
    # Runs at 01:00 each Saturday and Sunday
    - cron: '0 1 * * 0,6'
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run get-playlists
      - name: prepare commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add _data
      - name: push commit
        run: |
          if [[ $(git status --porcelain) ]]; then
          git commit -m "Add TestTafel Spotify playlist data"
          git push
          fi
