name: Bundle JS

on:
  push:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - run: npm install
      - run: npm run build:js
      - name: prepare commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add js
      - name: push commit
        run: |
          if [[ $(git status --porcelain) ]]; then
          git commit -m "build js bundle"
          git push
          fi
